on:
  push:
  pull_request:
    branches:
      - master
    paths:
      - "src/**/*"

name: Coverage Report

jobs:

  coverage:
    name: Build Coverage Report
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - name: Use Node.js 10.x
        uses: actions/setup-node@v3
        with:
          node-version: 10.x

      - name: npm install, make test-coverage
        run: |
          npm install
          npm run test:coverage

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          path-to-lcov: ./coverage/lcov.info # optional (default value)

      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
